- released/multi_provider_setup/modules/envinstance-cloudfoundry/provider.tf
- released/subaccount_dev_setup/modules/envinstance-cloudfoundry/provider.tf
* Sync all sap/btp provider version. In the future we can do a simple search and replace
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Alignment
```
n/a
> chore(config): prep version sync

- .github/dependabot.yml
* Adding Terraform package ecosystem to weekly check of dependabot
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: improvement of infrastructure
```
n/a
> chore(workflow): add Terraform package ecosystem to dependabot

- .devcontainer/default/devcontainer.json
- .devcontainer/withenvfile/devcontainer.json
- .gitignore
* Add devcontainer setup to ease demos
```
[ ] Bugfix
[X] Feature
```
n/a
> feat: add devcontainer setup

- released/modules/envinstance-cloudfoundry/outputs.tf
- released/uc_multi_provider_setup/README.md
- released/uc_subaccount_setup/README.md
Reverts SAP-samples/btp-terraform-samples#17
> Revert "add cf org name to output variables + fix typos"

- released/modules/envinstance-cloudfoundry/outputs.tf
* Expose cf org name
```
[ ] Bugfix
[x] Feature
```
> add cf org name

- released/modules/cloudfoundry-space/outputs.tf
* Adds the cf space name to the output variables of the cf space module
```
[ ] Bugfix
[ x] Feature
```
> add cf space name to output

- released/uc_dev-test-prod/uc_subaccount_setup/variables.tf
* Fix issue in description of variables
```
[x] Bugfix
[ ] Feature
```
> fix wrong description for some variables (copy-and-paste issue)

- released/uc_dev-test-prod/main.tf
* ...
```
[ ] Bugfix
[ ] Feature
```
> Add tst and prd landscape into the locals variables

- released/uc_dev-test-prod/terraform.tfvars
* Switch default CLI server url to the one used for SAP customers/partners
```
[ ] Bugfix
[X] Feature
```
> switch default CLI server url

- released/uc_dev-test-prod/terraform.tfvars
* Improves the readability of the tfvars file.
```
[ ] Bugfix
[ ] Feature
```
> cleanup tfvars for better readability and usage

- .github/workflows/uc_dev-test-prod.yml
- released/modules/cloudfoundry-space/provider.tf
- released/modules/envinstance-cloudfoundry/provider.tf
- released/uc_multi_provider_setup/provider.tf
- released/uc_subaccount_setup/provider.tf
- released/uc_trial_cf_deployment/provider.tf
* Update the provider versions and add additional workflow to run use case "dev/tst/prod landscape"
```
[ ] Bugfix
[x] Feature
```
> Update to 0.2.0 version

- released/uc_dev-test-prod/provider.tf
- released/uc_dev-test-prod/uc_subaccount_setup/main.tf
- released/uc_dev-test-prod/uc_subaccount_setup/provider.tf
* Remove comments that address features only available with version 0.2.0
```
[ ] Bugfix
[ ] Feature
```
> remove comments for upcoming 0.2.0 version

- released/modules/sap_build_apps/standard/outputs.tf
- released/uc_sap_build_apps/main.tf
- released/uc_sap_build_apps/outputs.tf
- released/uc_sap_build_apps/provider.tf
- released/uc_sap_build_apps/terraform.tfvars
- released/uc_sap_build_apps/variables.tf
* removes all cf dependencies from use case with SAP Build Apps
```
[ ] Bugfix
[x] Feature
```
> Remove dependency with cf for SAP Build Apps

- released/uc_multi_provider_setup/README.md
- released/uc_subaccount_setup/README.md
Adds the missing closing quotes to the var-file configuration option in the use case documentation
```
[ ] Bugfix
[ ] Feature
```
> docs: Add missing closing quotes for -var-file option in use case documentation

- released/modules/cloudfoundry-service-instance/provider.tf
- released/modules/cloudfoundry-space/provider.tf
- released/modules/envinstance-cloudfoundry/provider.tf
- released/modules/sap_build_apps/standard/provider.tf
- released/uc_btp_resillient_apps/provider.tf
- released/uc_dev-test-prod/provider.tf
- released/uc_dev-test-prod/uc_subaccount_setup/provider.tf
- released/uc_multi_provider_setup/provider.tf
- released/uc_sap_build_apps/provider.tf
- released/uc_subaccount_setup/provider.tf
- released/uc_trial_cf_deployment/provider.tf
* Update the provider version for SAP BTP and Cloud Foundry to the latest version
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: version update
```
n/a
> chore: version update of SAP BTP and CF provider

- released/modules/cloudfoundry-service-instance/variables.tf
- released/modules/cloudfoundry-space/variables.tf
- released/modules/envinstance-cloudfoundry-apiurl/variables.tf
- released/modules/envinstance-cloudfoundry/outputs.tf
- released/modules/sap_build_apps/standard/main.tf
- released/modules/sap_build_apps/standard/outputs.tf
- released/modules/sap_build_apps/standard/variables.tf
- released/uc_btp_resillient_apps/main.tf
- released/uc_btp_resillient_apps/provider.tf
- released/uc_btp_resillient_apps/terraform.tfvars
- released/uc_btp_resillient_apps/variables.tf
- released/uc_dev-test-prod/main.tf
- released/uc_dev-test-prod/provider.tf
- released/uc_dev-test-prod/terraform.tfvars
- released/uc_dev-test-prod/uc_subaccount_setup/main.tf
- released/uc_dev-test-prod/uc_subaccount_setup/variables.tf
- released/uc_multi_provider_setup/main.tf
- released/uc_multi_provider_setup/provider.tf
- released/uc_multi_provider_setup/variables.tf
- released/uc_sap_build_apps/main.tf
- released/uc_sap_build_apps/outputs.tf
- released/uc_sap_build_apps/provider.tf
- released/uc_sap_build_apps/terraform.tfvars
- released/uc_sap_build_apps/variables.tf
Just code formatting --> `terraform fmt -recursive .`
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: code formatting
```
> fix: code format

- released/modules/envinstance-cloudfoundry/provider.tf
- released/modules/sap_build_apps/standard/provider.tf
- released/uc_btp_resillient_apps/provider.tf
- released/uc_dev-test-prod/provider.tf
- released/uc_dev-test-prod/uc_subaccount_setup/provider.tf
- released/uc_multi_provider_setup/provider.tf
- released/uc_sap_build_apps/provider.tf
- released/uc_subaccount_setup/provider.tf
- released/uc_trial_cf_deployment/provider.tf
* Update of BTP Provider version to lates
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: version upgrade
```
n/a
> chore: update of BTP provider version

- released/uc_sap_build_apps/main.tf
* This terraform script execution was failing because the `SAP Build App` requires quota as well.
```
[x] Bugfix
[ ] Feature
```
> added quota for sap_build_apps

- in-development/discovery_center/mission_4024/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- in-development/discovery_center/mission_4024/provider.tf
- in-development/uc_btp_resillient_apps/provider.tf
- in-development/uc_multi_provider_setup/provider.tf
- in-development/uc_subaccount_setup/provider.tf
- in-development/uc_trial_cf_deployment/provider.tf
- released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
- released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/services_apps/sap_build_apps/provider.tf
* This PR updates the Terraform provider version to the latest one namely `0.5.0-beta1`
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Dependency update
```
n/a
> chore: update Terraform provider version to 0.5.0-beta1

- .github/workflows/integration_tests.yml
* Add initial integration test workflow
```
[ ] Bugfix
[x] Feature
```
> Add integration test workflow

- in-development/uc_subaccount_setup/README.md
* fixes #54 
```
[X] Bugfix
[ ] Feature
```
n/a
> fix: broken link

- released/discovery_center/mission_4038/README.md
- released/discovery_center/mission_4038/main.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4038/sample.tfvars
- released/discovery_center/mission_4038/variables.tf
Use Case: Gain real-time visibility into SAP Ariba Procurement Operations ([mission](https://discovery-center.cloud.sap/missiondetail/4038))
> DC Mission: Extract your Ariba Spend Data using SAP Integration Suite (4038)

- released/discovery_center/mission_4327/setup_subaccount_cf/README.md
- released/discovery_center/mission_4327/setup_subaccount_kyma/README.md
Documentation update for the discovery center mission 4327
@lechnerc77 Could you please review ? I have updated the known issues of the readme.md in the mission_4327.
> Documentation update for Discovery center mission 4327

- GET_STARTED.md
* add button as shortcut to open GitHub Codespaces
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
n/a
> feat: add codespace button

- .devcontainer/devcontainer.json
- .devcontainer/withenvfile/devcontainer.json
- GET_STARTED.md
- released/discovery_center/mission_3260/provider.tf
- released/discovery_center/mission_4024/provider.tf
- released/discovery_center/mission_4033/app_susbscriptions/app_subscriptions_setup.tf
- released/discovery_center/mission_4033/provider.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4172/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_kyma/provider.tf
- released/discovery_center/mission_4356/provider.tf
- released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
- released/modules/environment/kyma/envinstance_kyma/envinstance_kyma.tf
- released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/multi_provider_setup/provider.tf
- released/usecases/resillient_apps/provider.tf
- released/usecases/services_apps/sap_build_apps/provider.tf
- released/usecases/subaccount_setup/provider.tf
- released/usecases/trial_cf_deployment/provider.tf
* upgrade BTP Terraform provider version
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Upgrade TF provider version
```
n/a
> chore: provider version upgrade

- in-development/uc_kyma_gitops_fluxcd/README.md
- in-development/uc_kyma_gitops_fluxcd/main.tf
- in-development/uc_kyma_gitops_fluxcd/outputs.tf
- in-development/uc_kyma_gitops_fluxcd/provider.tf
- in-development/uc_kyma_gitops_fluxcd/variables.tf
* This PR superseeds PR #46 moving the implementation into the new repo structure
```
[ ] Bugfix
[X] Feature
```
n/a
> feat: move kyma flux pr to new structure

- GET_STARTED.md
- released/discovery_center/mission_3260/provider.tf
- released/discovery_center/mission_4024/provider.tf
- released/discovery_center/mission_4033/app_susbscriptions/app_subscriptions_setup.tf
- released/discovery_center/mission_4033/provider.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4172/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_kyma/provider.tf
- released/discovery_center/mission_4356/provider.tf
- released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
- released/modules/environment/kyma/envinstance_kyma/envinstance_kyma.tf
- released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/multi_provider_setup/provider.tf
- released/usecases/resillient_apps/provider.tf
- released/usecases/services_apps/sap_build_apps/provider.tf
- released/usecases/subaccount_setup/provider.tf
- released/usecases/trial_cf_deployment/provider.tf
* Update TF provider version to latest
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: provider version update
```
n/a
> chore: update Terraform provider version number

- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup_variables.tf
* Fix issue in the definition of variables.tf for dev / test / prod use case. This issue became transparent after running the GItHub workflow for the tests of use cases. See https://github.com/SAP-samples/btp-terraform-samples/actions/runs/6944977658/job/18893312712 
```
[x] Bugfix
[ ] Feature
```
> fix naming for Integration Test as "unit"

- released/usecases/kyma_devcontainer_runtime/README.md
- released/usecases/kyma_devcontainer_runtime/main.tf
- released/usecases/kyma_devcontainer_runtime/outputs.tf
- released/usecases/kyma_devcontainer_runtime/variables.tf
- released/usecases/kyma_devcontainer_runtime/version.tf
Yet another usecase. Shows how kyma on SAP BTP can be used to host a [devcontainer](https://containers.dev/implementors/spec/) runtime.
```
[ ] Bugfix
[x] Feature
```
> feat: kyma devcontainer runtime usecase

- released/discovery_center/mission_3260/provider.tf
- released/discovery_center/mission_4024/provider.tf
- released/discovery_center/mission_4033/app_susbscriptions/app_subscriptions_setup.tf
- released/discovery_center/mission_4033/provider.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4172/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_kyma/provider.tf
- released/discovery_center/mission_4356/provider.tf
- released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
- released/modules/environment/kyma/envinstance_kyma/envinstance_kyma.tf
- released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/kyma_devcontainer_runtime/version.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/multi_provider_setup/provider.tf
- released/usecases/resillient_apps/provider.tf
- released/usecases/services_apps/sap_build_apps/provider.tf
- released/usecases/subaccount_setup/provider.tf
- released/usecases/trial_cf_deployment/provider.tf
* Update to RC2
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: RC upgrade
```
n/a
> chore: rc2 update

- .github/workflows/links-watcher-cron.yml
* Lychee-verse Update and fix
```
[X] Bugfix
[ ] Feature
```
n/a
> chore: fix link checker

- GET_STARTED.md
- released/discovery_center/mission_3260/provider.tf
- released/discovery_center/mission_4024/provider.tf
- released/discovery_center/mission_4033/app_susbscriptions/app_subscriptions_setup.tf
- released/discovery_center/mission_4033/provider.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4172/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_kyma/provider.tf
- released/discovery_center/mission_4356/provider.tf
- released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
- released/modules/environment/cloudfoundry/serviceinstance_cf/serviceinstance_cf.tf
- released/modules/environment/cloudfoundry/space_cf/space_cf.tf
- released/modules/environment/kyma/envinstance_kyma/envinstance_kyma.tf
- released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/kyma_devcontainer_runtime/version.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/README.md
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/multi_provider_setup/provider.tf
- released/usecases/resillient_apps/provider.tf
- released/usecases/services_apps/sap_build_apps/provider.tf
- released/usecases/subaccount_setup/provider.tf
- released/usecases/trial_cf_deployment/provider.tf
* Update to latest Terraform version
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update TF version
```
Also updated CF Versions
> chore: update to TF provider 1.0.0

- released/usecases/trial_cf_deployment/assets/helloterraformapp/package-lock.json
- released/usecases/trial_cf_deployment/assets/helloterraformapp/package.json
* Fixes CVE-2023-26159
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Security fix for CVE-2023-26159
```
n/a
> fix: CVE-2023-26159

- released/discovery_center/mission_4024/README.md
- released/discovery_center/mission_4024/main.tf
* fix workzone entitlement issue with plan free 
* improve readme
> Fix mission 4024

- released/discovery_center/mission_4024/variables.tf
* enable service plan partner for sap build apps service entitlement
```
[ ] Bugfix
[x ] Feature
[ ] Other
```
> enhance mission 4024

- .gitignore
- released/dsag/betriebstag2024/exercises/EXERCISE1/README.md
- released/dsag/betriebstag2024/exercises/EXERCISE1/SOLUTION_EX1/provider.tf
- released/dsag/betriebstag2024/exercises/EXERCISE2/SOLUTION_EX2/provider.tf
- released/dsag/betriebstag2024/exercises/EXERCISE3/SOLUTION_EX3/provider.tf
- released/dsag/betriebstag2024/exercises/EXERCISE4/SOLUTION_EX4/provider.tf
- released/dsag/betriebstag2024/exercises/EXERCISE5/SOLUTION_EX5/provider.tf
- released/dsag/betriebstag2024/exercises/EXERCISE6/SOLUTION_EX6/provider.tf
- released/dsag/betriebstag2024/exercises/EXERCISE7/SOLUTION_EX7/provider.tf
- released/dsag/betriebstag2024/solution/provider.tf
> chore: update provider version for HandsOn

- released/dsag/betriebstag2024/exercises/EXERCISE1/README.md
- released/dsag/betriebstag2024/exercises/EXERCISE2/README.md
- released/dsag/betriebstag2024/exercises/EXERCISE6/README.md
- released/dsag/betriebstag2024/exercises/EXERCISE7/README.md
* Refine documentation for Handson at DSAG Betriebstage 2024
* Fix Typos
```
[ ] Bugfix
[ ] Feature
```
n/a
> docs: refine tutorial for DSAG Betriebstage

- released/discovery_center/mission_3260/provider.tf
- released/discovery_center/mission_4024/provider.tf
- released/discovery_center/mission_4033/app_susbscriptions/app_subscriptions_setup.tf
- released/discovery_center/mission_4033/provider.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4172/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_kyma/provider.tf
- released/discovery_center/mission_4356/provider.tf
- released/modules/environment/cloudfoundry/envinstance_cf/envinstance_cf.tf
- released/modules/environment/kyma/envinstance_kyma/envinstance_kyma.tf
- released/modules/services_apps/sap_build_apps/standard/sap_build_apps.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/kyma_devcontainer_runtime/version.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/multi_provider_setup/provider.tf
- released/usecases/resillient_apps/provider.tf
- released/usecases/services_apps/sap_build_apps/provider.tf
- released/usecases/subaccount_setup/provider.tf
- released/usecases/trial_cf_deployment/provider.tf
* Upgrade provider to latest version of Terraform provider for SAP BTP (1.1.0)
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: version update
```
n/a
> chore: upgrade samples to latest version of Terraform provider

- released/dsag/betriebstag2024/exercises/EXERCISE1/README.md
- released/dsag/betriebstag2024/exercises/EXERCISE7/README.md
* Fix minor issues for code to be used for DSAG Bestriebstage 2024 hands-on session.
```
[x] Bugfix
[ ] Feature
```
> Dsag 2024 bt proposals

- .github/workflows/scenario-test.yml
This PR introduces an actions YAML file to run tests against both the stable version of the BTP Terraform provider and the local version.
```
[ ] Bugfix
[x] Feature
```
> Add GitHub actions to validate provider against key test-samples

- .github/workflows/scenario-test.yml
Fixed the issue that caused failure in creating issues when the workflow failed. The problem was with the "body" string; it wasn't terminating properly due to the presence of "\n" in the body, which has now been fixed. Additionally, we observed failures due to CF instance name already existing. To address this, we are updating the instance name using the sed command in the workflow.
```
[ ] Bugfix
[ ] Feature
```
> chore: Fix issue creation

- .gitignore
- released/usecases/genai-setup/main.tf
- released/usecases/genai-setup/modules/ai/ai.tf
- released/usecases/genai-setup/modules/ai/ai_outputs.tf
- released/usecases/genai-setup/modules/ai/ai_variables.tf
- released/usecases/genai-setup/modules/hana-cloud/hana_cloud.tf
- released/usecases/genai-setup/modules/hana-cloud/hana_cloud_outputs.tf
- released/usecases/genai-setup/modules/hana-cloud/hana_cloud_variables.tf
- released/usecases/genai-setup/provider.tf
- released/usecases/genai-setup/sample.tfvars
- released/usecases/genai-setup/variables.tf
This PR adds the newly available vector engine for HANA Cloud to the genAI use case.
```
[ ] Bugfix
[x] Feature
```
> Update gen ai use case

- released/usecases/abap_env_in_subaccount/README.md
- released/usecases/abap_env_in_subaccount/main.tf
- released/usecases/abap_env_in_subaccount/provider.tf
- released/usecases/abap_env_in_subaccount/variables.tf
- released/usecases/abap_env_setup/README.md
* Variant of ABAP env setup
```
[ ] Bugfix
[X] Feature
```
n/a
> Abap env small

- released/discovery_center/mission_3260/main.tf
- released/discovery_center/mission_4024/main.tf
- released/discovery_center/mission_4038/main.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/main.tf
- released/discovery_center/mission_4327/setup_subaccount_kyma/main.tf
- released/usecases/resillient_apps/main.tf
- released/usecases/services_apps/sap_build_apps/main.tf
* Some samples used the `uuid()` function to create UUIDs when defining local variables. However this function get executed every time the block is hit and consequently leads to a diff
* This PR replaces the UUID function with the UUID resource as recommended by Hashicorp (see [resource documentation](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/uuid) and [uuid function documentation](https://developer.hashicorp.com/terraform/language/functions/uuid))
```
[X] Bugfix
[ ] Feature
```
n/a
> fix: usage of uuid

- released/terraform-be/README.md
- released/terraform-be/k8sasbackend/README.md
- released/terraform-be/k8sasbackend/backend.tf
- released/terraform-be/k8sasbackend/main.tf
- released/terraform-be/k8sasbackend/variables.tf
Added the remote backend setup to securely store the Terraform state file.
```
[ ] Bugfix
[ ] Feature
```
> Update remote backend configuration

- released/terraform-be/README.md
- released/terraform-be/k8sasbackend/README.md
- released/terraform-be/k8sasbackend/backend.tf
- released/terraform-be/k8sasbackend/main.tf
- released/terraform-be/k8sasbackend/provider.tf
- released/terraform-be/k8sasbackend/variables.tf
* Editorial rework of backend description
```
[ ] Bugfix
[ ] Feature
```
n/a
> docs: editorial rework

- in-development/mission_4024_multi_step/1_main_config/locals.tf
- in-development/mission_4024_multi_step/1_main_config/main.tf
- in-development/mission_4024_multi_step/1_main_config/outputs.tf
- in-development/mission_4024_multi_step/1_main_config/provider.tf
- in-development/mission_4024_multi_step/1_main_config/sample.tfvars
- in-development/mission_4024_multi_step/1_main_config/variables.tf
- in-development/mission_4024_multi_step/2_disable_default_login/main.tf
- in-development/mission_4024_multi_step/2_disable_default_login/provider.tf
- in-development/mission_4024_multi_step/2_disable_default_login/sample.tfvars
- in-development/mission_4024_multi_step/2_disable_default_login/variables.tf
- in-development/mission_4024_multi_step/README.md
- in-development/mission_4024_multi_step/common_sample.tfvars
* add multi step feature to get further requirements (edit default trust in step 2) resolved for quick account setup (in development)
[x] Feature
> add multi step to mission 4024

- released/discovery_center/mission_4327/setup_subaccount_cf/main.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
- released/discovery_center/mission_4327/setup_subaccount_cf/samples.tfvars
- released/discovery_center/mission_4327/setup_subaccount_cf/testsamples.tfvars
- released/discovery_center/mission_4327/setup_subaccount_cf/variables.tf
Updated the discovery centre mission 4327 with SAP/cloudfoundry provider.
```
[ ] Bugfix
[ ] Feature
```
> chore: update mission 4327

- .github/workflows/scenario-test.yml
Updates the workflow which would over write the variable for cf_org_user and cf_space_manager
```
[ ] Bugfix
[ ] Feature
```
> chore: update scenario-test.yml

- .github/workflows/scenario-test.yml
- released/discovery_center/mission_4327/setup_subaccount_cf/testsamples.tfvars
This PR will fix the issues which caused the workflow failure.
```
[x] Bugfix
[ ] Feature
```
> chore: update scenario tests for mission 4327

- in-development/mission_3774_sap_task_center/README.md
* ...
```
[ ] Bugfix
[ ] Feature
```
> adding README.md for Task Center 

- .github/workflows/terraform_format_check.yml
- .github/workflows/terraform_validate.yml
* Add GH Action check to execute a terraform validate on changed files
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Code quality
```
See https://developer.hashicorp.com/terraform/cli/commands/validate
> chore: add tf validation 

- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup_outputs.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup_variables.tf
* This PR removes the dependency to the envinstance_cf module. This allows a better separation of the use case.
```
[ ] Bugfix
[x] Feature
```
> remove dependency to envinstance module

- released/modules/btp-cf/btp-cf-env-instance/README.md
- released/modules/btp-cf/btp-cf-env-instance/btp_env_cf.tf
- released/modules/btp-cf/btp-cf-env-instance/btp_env_cf_outputs.tf
- released/modules/btp-cf/btp-cf-env-instance/btp_env_cf_variables.tf
Introduced a new module for btp cf provider. This module will setup a cf-org and add a new org user using btp cloud foundry provider
```
[ ] Bugfix
[ ] Feature
```
> chore: update new module for btp-cf provider

- released/usecases/trial_cf_deployment/assets/helloterraformapp/package-lock.json
- released/usecases/trial_cf_deployment/assets/helloterraformapp/package.json
* Security fix
* Version update
```
[X] Bugfix
[ ] Feature
```
n/a
> Security fix

- released/discovery_center/mission_3061/step2/main.tf
- released/discovery_center/mission_3061/step2/variables.tf
Match output to variables between steps
> fix: mission3061 match output and variables

- released/dsag/betriebstag2024/exercises/EXERCISE7/README.md
- released/dsag/betriebstag2024/exercises/EXERCISE7/SOLUTION_EX7/provider.tf
- released/dsag/betriebstag2024/solution/provider.tf
* ...
```
[ ] Bugfix
[ ] Feature
```
> chore: update cf provider version

- in-development/discovery_center/mission_3585/README.md
Get Started on SAP BTP with SAPUI5/Fiori - Create a Hello World App
readme for new mission
* ...
new Readme
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
-
> Create README.md mission 3585

- released/discovery_center/mission_3061/step1/variables.tf
- released/discovery_center/mission_3061/step2/variables.tf
* Fix regex validation for ABAP SID
```
[X] Bugfix
[ ] Feature
```
n/a
> fix: regex validation

- .devcontainer/devcontainer.json
- .devcontainer/withenvfile/devcontainer.json
* Remove automatic installation of XDG tools as in some network configurations the install fails due to apt not being able to call to extern
```
[X] Bugfix
[ ] Feature
```
n/a
> fix: error during installation of xdg util

- released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
This PR updates the cf provider to version 0.2.1-beta
```
[ ] Bugfix
[ ] Feature
```
> chore: Update mission_4327 cf provider version

- released/discovery_center/mission_3774/step1/sample.tfvars
- released/discovery_center/mission_3774/step2/sample.tfvars
* Adjust `samples.tfvars`to reflect renaming of `variables.tfvars`
```
[X] Bugfix
[ ] Feature
```
n/a
> fix: adjust samples.tfvars to be in line with variables.tfvars

- released/discovery_center/mission_3774/step1/variables.tf
* fix typo in mission 3774
```
[x] Bugfix
[ ] Feature
```
> fix typo in mission 3774

- released/discovery_center/mission_3348/README.md
- released/discovery_center/mission_3348/locals.tf
- released/discovery_center/mission_3348/main.tf
- released/discovery_center/mission_3348/outputs.tf
- released/discovery_center/mission_3348/provider.tf
- released/discovery_center/mission_3348/sample.tfvars
- released/discovery_center/mission_3348/variables.tf
* dc mission 3348
```
[ ] Bugfix
[X] Feature
```
> [NEW] dc mission 3348

- released/discovery_center/mission_3774/step1/main.tf
- released/discovery_center/mission_3774/step1/outputs.tf
- released/discovery_center/mission_3774/step1/provider.tf
- released/discovery_center/mission_3774/step1/sample.tfvars
- released/discovery_center/mission_3774/step1/variables.tf
- released/discovery_center/mission_3774/step2/main.tf
- released/discovery_center/mission_3774/step2/variables.tf
* This PR applies some naming conventions for the QAS on SAP Discovery Center.
```
[ ] Bugfix
[x] Feature
```
> Apply naming convention for mission 3774

- .github/workflows/scenario-test.yml
- released/discovery_center/mission_4327/setup_subaccount_cf/main.tf
Updated the mission to take random uuid for the cf org creation and updated the GitHub action to co-operate with the changes.
```
[ ] Bugfix
[ ] Feature
```
> chore: Update DC mission 4327

- released/discovery_center/mission_3252/main.tf
- released/discovery_center/mission_3252/provider.tf
- released/discovery_center/mission_3252/samples.tfvars
- released/discovery_center/mission_3252/variables.tf
Changed region to eu10 for mission 3252
> Changed region to eu10 for mission 3252

- released/discovery_center/mission_3252/README.md
- released/discovery_center/mission_3252/main.tf
- released/discovery_center/mission_3252/outputs.tf
- released/discovery_center/mission_3252/provider.tf
- released/discovery_center/mission_3252/samples.tfvars
- released/discovery_center/mission_3252/variables.tf
Update DC Mission 3252 (Kyma) for QAS
* auto-select kyma region if kyma instance parameters are not set
* update Readme
* add outputs.tf
* add custom_idp
* rename kyma variables
* add validation
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update DC Mission 3252 (Kyma) for QAS
```
> Update DC Mission 3252 (Kyma) for QAS

- released/discovery_center/mission_3248_trial/README.md
- released/discovery_center/mission_3248_trial/step1/README.md
- released/discovery_center/mission_3248_trial/step1/locals.tf
- released/discovery_center/mission_3248_trial/step1/main.tf
- released/discovery_center/mission_3248_trial/step1/outputs.tf
- released/discovery_center/mission_3248_trial/step1/provider.tf
- released/discovery_center/mission_3248_trial/step1/samples.tfvars
- released/discovery_center/mission_3248_trial/step1/variables.tf
- released/discovery_center/mission_3248_trial/step2/README.md
- released/discovery_center/mission_3248_trial/step2/locals.tf
- released/discovery_center/mission_3248_trial/step2/main.tf
- released/discovery_center/mission_3248_trial/step2/outputs.tf
- released/discovery_center/mission_3248_trial/step2/provider.tf
- released/discovery_center/mission_3248_trial/step2/variables.tf
Create terraform sample for Discovery Center mission 3248 ("Prepare an Account for ABAP Trial")
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Add new DC mission
```
> Dc mission 3248

- released/discovery_center/mission_3248_trial/step1/outputs.tf
* Adds missing output to mission 3248 (required for QAS)
```
[x] Bugfix
[ ] Feature
```
> add missing landscape label

- released/discovery_center/mission_4104/main.tf
- released/discovery_center/mission_4104/outputs.tf
- released/discovery_center/mission_4104/provider.tf
- released/discovery_center/mission_4104/sample.tfvars
- released/discovery_center/mission_4104/variables.tf
Ensure QAS compliance and improve DC mission 4104
* Add outputs.tf
* Minor renaming
* Use `custom_idp` variable
* Improve documentation and validation of Datasphere parameters, and add them to sample.tfvars.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Ensure QAS compliance and improve DC mission 4104
```
> Ensure compliance for mission 4104

- .github/workflows/scenario-test.yml
Update path change for scenario tests workflow.
```
[ ] Bugfix
[ ] Feature
```
> chore: Update workflow scenario-test.yml

- released/cicd/setup_subaccount_cf/README.md
Fixing the issue #282
Update path of the readme.md
```
[ ] Bugfix
[ ] Feature
```
> chore: Update README.md mission 4327

- released/discovery_center/mission_4327/step2_kyma/provider.tf
- released/usecases/trial_cf_deployment/provider.tf
Updating BTP terraform provider version to 1.5.0
```
[ ] Bugfix
[ ] Feature
```
> chore: update btp provider version 1.5.0

- .github/workflows/terraform_format_check.yml
Update workflow for printing the file path error where the fmt check is breaking.
```
[ ] Bugfix
[ ] Feature
```
> chore: Update terraform_format_check.yml

- released/discovery_center/mission_4038/main.tf
- released/discovery_center/mission_4038/outputs.tf
- released/discovery_center/mission_4038/provider.tf
- released/discovery_center/mission_4038/variables.tf
- released/discovery_center/mission_4356/step1/main.tf
- released/discovery_center/mission_4356/step1/outputs.tf
- released/discovery_center/mission_4356/step1/provider.tf
- released/discovery_center/mission_4356/step1/variables.tf
- released/discovery_center/mission_4356/step2/provider.tf
* ...
```
[X] Bugfix
[ ] Feature
[X] Other... Please describe: Added free plan for integration suite 
```
> Mission: 4356 & 4038- Added free plan for integration suite & minor fix

- CONTRIBUTING.md
* Update contribution guidelines in accordance to updated OSPO requirements
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update contribution guidelines
```
n/a
> docs: update contribution guideline (OSPO)

- released/usecases/trial_cf_deployment/assets/helloterraformapp/package-lock.json
- released/usecases/trial_cf_deployment/assets/helloterraformapp/package.json
* Fix security vulnerabilities
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Security vulberabilities
```
See https://github.com/SAP-samples/btp-terraform-samples/security/dependabot/13
> fix: security vulnerabilities

- released/SAP-Inside-Tracks/SITBLR2024/provider.tf
- released/discovery_center/mission_3348/provider.tf
- released/discovery_center/mission_3488/step1/provider.tf
- released/discovery_center/mission_3488/step2/provider.tf
- released/discovery_center/mission_3945/provider.tf
- released/discovery_center/mission_4033/step1/provider.tf
- released/discovery_center/mission_4033/step2/provider.tf
- released/discovery_center/mission_4172/step1/provider.tf
- released/discovery_center/mission_4327/step1/provider.tf
- released/discovery_center/mission_4327/step2_cf/provider.tf
- released/discovery_center/mission_4356/step1/provider.tf
- released/discovery_center/mission_4371/step1/provider.tf
- released/discovery_center/mission_4371/step2/provider.tf
- released/modules/btp-cf/btp-cf-env-instance/btp_env_cf.tf
- released/usecases/cf_enable_application_runtime_memory/provider.tf
- released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/dev_test_prod_setup/provider.tf
- released/usecases/multi_account_setup/modules/subaccount_setup/subaccount_setup.tf
- released/usecases/multi_account_setup/provider.tf
- released/usecases/role_assignments/provider.tf
- released/usecases/services_apps/sap_build_code/step1/provider.tf
- released/usecases/services_apps/sap_build_code/step2/main.tf
- released/usecases/services_apps/sap_build_code/step2/provider.tf
Updated the BTP Terraform provider versions across all missions and modified the use case in services_apps/sap_build_code/step2/main.tf to make it incompatible with the CloudFoundry provider.
```
[ ] Bugfix
[ ] Feature
```
> chore: update provider versions

- released/dsag/betriebstag2024/exercises/EXERCISE4/SOLUTION_EX4/variables.tf
- released/dsag/betriebstag2024/exercises/EXERCISE5/SOLUTION_EX5/variables.tf
- released/dsag/betriebstag2024/exercises/EXERCISE6/SOLUTION_EX6/variables.tf
* Wrong region in some solutions of DSAG sample
```
[X] Bugfix
[ ] Feature
```
n/a
> fix: wrong region in DSAG solutions for trial

- released/SAP-Inside-Tracks/SITBLR_MAR_2025/exercises/EXERCISE1/README.md
fixes documentation SIT
```
[ ] Bugfix
[ ] Feature
```
> fix: documentation fixes

- released/cicd/setup_subaccount_cf/main.tf
- Timestamp
- Scenario
Can be used for filtering the automated tests
```
[ ] Bugfix
[ ] Feature
[] Documentation content changes
[x] Other... Please describe: Added labels
```
Useful for scenarios, where these automated tests can be filtered out seperately
> chore: Add labels

- .github/workflows/scenario-test.yml
Disabling the pipeline's cronjob since it is unstable due to platform related issues. keeping it active for the manual workflow triggers.
```
[x] Bugfix
[ ] Feature
```
> fix: disabling scenario test pipeline's cronjob

- released/SAP-Inside-Tracks/SITBLR_JUNE_2025/README.md
* adds quotes to username variables for windows
* closes #464
```
[ ] Bugfix
[ ] Feature
```
> fix: quotes for username on Windows

- released/discovery_center/mission_3061/step2/sample.tfvars
- released/discovery_center/mission_3260/step2/sample.tfvars
- released/discovery_center/mission_3488/step2/sample.tfvars
- released/discovery_center/mission_3501/step2/sample.tfvars
- released/discovery_center/mission_3680/step2/sample.tfvars
- released/discovery_center/mission_4033/step2/sample.tfvars
- released/discovery_center/mission_4172/step2/sample.tfvars
- released/discovery_center/mission_4172/step2/variables.tf
- released/discovery_center/mission_4327/step2_cf/sample.tfvars
* Add missing tfvar files for several missions
* closes #468
```
[X] Bugfix
[ ] Feature
```
> fix: missing tfvar files for several missions

- released/SAP-Inside-Tracks/SITBLR_OCT_2024/readme.md
* Fix broken link to learning journey on Terraform
```
[ ] Bugfix
[ ] Feature
```
n/a
> fix: broken link to learning journey
