SAP-samples/btp-terraform-samples

released/modules/sap_build_apps/standard/main.tf
released/uc_sap_build_apps/main.tf

* ...
The Destination for the connection between SAP Build Apps and Visual Cloud Functions should be on the subaccount level not on the space level. Also the  destination creation should be in the module and not in the calling script.
move destination configuration from us_cap_build_apps to  sap_build_apps module
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe: Improvement for SAP Build Apps 
```

Move destination for SAP Build Apps VCF from space to subaccount

---

released/modules/envinstance-kyma/README.md
released/modules/envinstance-kyma/main.tf
released/modules/envinstance-kyma/outputs.tf
released/modules/envinstance-kyma/provider.tf
released/modules/envinstance-kyma/variables.tf

Adds a module to instantiate kyma clusters in a BTP account.
```hcl
module "k8s_runtime" {
source = "github.com/SAP-samples/btp-terraform-samples/released/modules/envinstance-kyma"
subaccount_id = btp_subaccount.kyma_gitops.id
name          = "my-cluster"
plan          = "trial"
}
```
```
[ ] Bugfix
[x] Feature
```

feat: module for kyma

---

released/discovery_center/mission_4024/locals.tf
released/discovery_center/mission_4024/main.tf
released/discovery_center/mission_4024/variables.tf

* Make service (plan) variables more machine-readable, to allow pipeline for Quick-Account-Setup solutions to more easily infer what are the service plan inputs
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: change structure of variables to follow conventions for Quick-Account-Setup
```

Use new convention for service plan variables, externalize service names as local variables

---

released/discovery_center/mission_4327/setup_subaccount_cf/README.md
released/discovery_center/mission_4327/setup_subaccount_cf/main.tf
released/discovery_center/mission_4327/setup_subaccount_cf/provider.tf
released/discovery_center/mission_4327/setup_subaccount_cf/testsamples.tfvars
released/discovery_center/mission_4327/setup_subaccount_cf/variables.tf

This PR fixes an issue that prevented successful execution of terraform destroy by addressing the removal of cf org members. Additionally, it updates the README.md to reflect these changes. Also we have removed the cf provider part from the provider.tf since we are not using it create any other cf resources.
We've introduced a new file, testsamples.tf, which enables automated testing of the mission using GitHub Actions.
```
[x] Bugfix
[ ] Feature
```

Update Discovery Center Mission 4327

---

released/discovery_center/mission_4024/provider.tf

`cli_server_url` is defined as a variable in variables.tf, but is not passed through to the provider and hence the default cannot be overwritten.
```
[x] Bugfix
[ ] Feature
```

fix: Add missing cli_server_url in provider.tf for mission 4024

---

released/modules/btp-cf/btp-cf-env-instance/btp_env_cf.tf
released/modules/btp-cf/btp-cf-env-instance/btp_env_cf_variables.tf
released/usecases/subaccount_setup/main.tf
released/usecases/subaccount_setup/provider.tf
released/usecases/subaccount_setup/variables.tf

This PR updates the subaccount setup in the use cases to use the BTP Cloud Foundry provider to set up the CF organization and add users to it.
```
[ ] Bugfix
[ ] Feature
```

chore: update usecases subaccount setup

---

released/usecases/services_apps/sap_build_code/step1/main.tf
released/usecases/services_apps/sap_build_code/step1/outputs.tf
released/usecases/services_apps/sap_build_code/step1/variables.tf
released/usecases/services_apps/sap_build_code/step2/main.tf
released/usecases/services_apps/sap_build_code/step2/variables.tf

* This PR updates the variable names for the SAP Build Code use case.
```
[ ] Bugfix
[x] Feature
```

Varnames update sap build code

---

released/usecases/subaccount_setup/main.tf
released/usecases/subaccount_setup/outputs.tf
released/usecases/subaccount_setup/provider.tf
released/usecases/subaccount_setup/variables.tf

* refinement of vars
```
[ ] Bugfix
[X] Feature
```
n/a

feat: refinement of setup

---

released/discovery_center/mission_3061/step1/outputs.tf
released/discovery_center/mission_3061/step1/variables.tf
released/discovery_center/mission_3061/step2/main.tf
released/discovery_center/mission_3061/step2/provider.tf
released/discovery_center/mission_3061/step2/variables.tf

* Fix naming conventions for QAS setup
* Add validation for ABAP system ID
```
[X] Bugfix
[ ] Feature
```
n/a

fix: naming conventions ABAP mission

---

released/discovery_center/mission_3585/outputs.tf

* removes two variables that are not needed
```
[x] Bugfix
[ ] Feature
```

remove unwanted outputs

---

in-development/mission_4024_multi_step/1_main_config/outputs.tf
released/discovery_center/mission_4024/outputs.tf

* Fixes the output of mission 4024 to read `sap_build_apps_subscription_url` instead of `sap_build_app_subscription_url`
```
[x] Bugfix
[ ] Feature
```
This is to a) align this with the product's actual name, b) make it consistent with the other occurrences in this repo and c) make the mission work for QAS. Plus a nicer description.

fix: Output sap_build_apps_subscription_url instead of sap_build_app_subscription_url, mission 4024

---

released/discovery_center/mission_3774/step1/locals.tf
released/discovery_center/mission_3774/step1/main.tf
released/discovery_center/mission_3774/step1/outputs.tf
released/discovery_center/mission_3774/step1/variables.tf
released/discovery_center/mission_3774/step2/provider.tf
released/discovery_center/mission_3774/step2/variables.tf

* QAS Adjustments (variable names, outputs) for mission 3774
* Removal of unused variables from step 2 of mission 3774
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: QAS Adjustments for mission 3774
```

review for QAS, remove unused vars

---

.devcontainer/withenvfile/devcontainer.json
.gitignore
tests/compliance/libs/constants/files_folders.py
tests/compliance/libs/constants/providers.py
tests/compliance/libs/constants/variables.py
tests/compliance/libs/inspect.py
tests/compliance/libs/inspection/provider.py
tests/compliance/libs/io/files.py
tests/compliance/libs/model/finding.py
tests/compliance/libs/model/provider.py
tests/compliance/scan_tf.py

* This PR provides a script that can review the TF scripts to that they are compliant with some naming conventions.
```
[ ] Bugfix
[x] Feature
```

Add compliance checks for TF scripts

---

released/discovery_center/mission_3260/main.tf
released/discovery_center/mission_3260/outputs.tf
released/discovery_center/mission_3260/provider.tf
released/discovery_center/mission_3260/samples.tfvars
released/discovery_center/mission_3260/variables.tf
released/discovery_center/mission_4024/main.tf

* clean-up mission 3260 (remove dependency to modules)
* make the code fit to use in quick-account-setup in SAP Discovery Center.
```
[ ] Bugfix
[x] Feature
```

clean-up code for usage in quick-account-setup (mission 3260)

---

released/discovery_center/mission_3945/README.md
released/discovery_center/mission_3945/locals.tf
released/discovery_center/mission_3945/main.tf
released/discovery_center/mission_3945/outputs.tf
released/discovery_center/mission_3945/provider.tf
released/discovery_center/mission_3945/sample.tfvars
released/discovery_center/mission_3945/variables.tf

* dc misison 3945
```
[ ] Bugfix
[X] Feature
```

[NEW] dc misison 3945

---

released/discovery_center/mission_3061/step1/variables.tf
released/discovery_center/mission_3061/step2/main.tf
released/discovery_center/mission_3061/step2/variables.tf

* Increases the timeouts for the ABAP service instance for DC mission 3061
* Removes email validation for users for DC mission 3061
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improve DC mission 3061
```
* The operations on the ABAP service instance, especially its creation, can take longer than 3h.
* The user identifier isn't necessarily an email for custom IdPs

increase timeouts, remove email validation

---

released/discovery_center/mission_3680/step1/main.tf
released/discovery_center/mission_3680/step1/output.tf
released/discovery_center/mission_3680/step1/samples.tfvars

* Adds smaller fixes to comply with naming convention. 
* Adds the hana_tools url to the output
```
[ ] Bugfix
[x] Feature
```

Naming conventions fix for mission 3680

---

released/discovery_center/mission_3061/step2/main.tf
released/discovery_center/mission_3061/step2/outputs.tf
released/discovery_center/mission_3248_trial/step2/outputs.tf

Improve outputs of DC missions 3061 and 3248 for QAS. Adds outputs for:
* Service instance ID
* Dashboard URL
* Service Key IDs
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Improve outputs of DC missions 3061 and 3248 for QAS
```

Improve outputs of DC missions 3061 and 3248 for QAS

---

released/terraform-be/README.md
released/terraform-be/s3asbackend/README.md
released/terraform-be/s3asbackend/backend.tf
released/terraform-be/s3asbackend/main.tf
released/terraform-be/s3asbackend/provider.tf
released/terraform-be/s3asbackend/variables.tf

Added sample scripts for configuring S3 as a Terraform backend
```
[ ] Bugfix
[ ] Feature
```

chore: sample for S3 as terraform backend

---

released/discovery_center/mission_4327/step1/main.tf
released/discovery_center/mission_4327/step1/outputs.tf

* Mission 4327: Remove current user from CF org users/admins (required for QAS)
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: QAS update for mission 4327
```
For QAS the current user might be in the list of CF org users and admins. This will lead to errors as the current user already has those roles and the API isn't idempotent.

Remove current user from CF org users/admins

---

released/discovery_center/mission_3260/locals.tf
released/discovery_center/mission_3260/main.tf
released/discovery_center/mission_3260/outputs.tf
released/discovery_center/mission_3260/provider.tf
released/discovery_center/mission_3260/sample.tfvars
released/discovery_center/mission_3260/variables.tf

* polished code to be consistent with other QAS missions (like 4024 or 3585)
```
[ ] Bugfix
[ ] Feature
[x] Clean-up code consistent with other mission scripts (like 4024 or 3585)
```

3260: Polishing the QAS enabled Mission

---

released/discovery_center/mission_3585_trial/README.md
released/discovery_center/mission_3585_trial/main.tf
released/discovery_center/mission_3585_trial/outputs.tf
released/discovery_center/mission_3585_trial/sample.tfvars
released/discovery_center/mission_3585_trial/variables.tf

* Mission owner requested to add cicd as optional app subscription
```
[ ] Bugfix
[x] Feature
```

3585_trial: add cicd (optional app subscription)

---

released/discovery_center/mission_3585/main.tf
released/discovery_center/mission_3585/outputs.tf
released/discovery_center/mission_3585/variables.tf

* Mission owner requested to remove cicd service because it is not used in the described use case
```
[ ] Bugfix
[ ] Feature
[x] Clean-up
```

3585: removed not used cicd service

---

released/discovery_center/mission_4441/minimal_setup_enterprise/step1/main.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step1/outputs.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step1/sample.tfvars
released/discovery_center/mission_4441/minimal_setup_enterprise/step1/variables.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step2/main.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step2/variables.tf

* polished code to be consistent with other QAS enabled missions (like 4024, 3585, ...)
```
[ ] Bugfix
[ ] Feature
[x] Clean-up code consistent with other mission scripts (like 4024 or 3585)
```

4441: Polished QAS enabled Mission

---

released/discovery_center/mission_4441/minimal_setup_enterprise/step1/main.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step1/outputs.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step1/variables.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step2/main.tf
released/discovery_center/mission_4441/minimal_setup_enterprise/step2/variables.tf

* Fix custom idp case for QAS enabled Mission
```
[x] Bugfix
[ ] Feature
```

4441: Fix custom idp cases for QAS enabled Mission

---

released/dsag/betriebstag2024/exercises/EXERCISE2/README.md
released/terraform-be/README.md

* Fix broken links in documentation
* closes #312
```
[ ] Bugfix
[ ] Feature
```
n/a

fix: broken links to Terraform documentation

---

released/discovery_center/mission_4441_trial/README.md
released/discovery_center/mission_4441_trial/main.tf
released/discovery_center/mission_4441_trial/outputs.tf
released/discovery_center/mission_4441_trial/sample.tfvars
released/discovery_center/mission_4441_trial/variables.tf

* Polished code to be consistent with other QAS missions (like 4024 or 3585)
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes (trial prerequisites added in README.md)
[x] Clean-up code consistent with other mission scripts (like 4024 or 3585)

4441_trial: Polishing the QAS enabled Mission

---

released/SAP-Inside-Tracks/SITBLR2024/provider.tf
released/SAP-Inside-Tracks/SITBLR2024/readme.md

Added a readme file and also modified the version of the BTP Provider used
```
[ ] Bugfix
[ ] Feature
```

Documentation for SIT

---

released/usecases/role_assignments/main.tf
released/usecases/role_assignments/provider.tf
released/usecases/role_assignments/readme.md
released/usecases/role_assignments/variables.tf

Added a new sample configuration for role collection assignments, This sample shows how to assign multiple users to various role collections.
```
[ ] Bugfix
[ ] Feature
```

chore: Added new sample for role collection assignments

---

released/usecases/dev_test_prod_setup/modules/subaccount_setup/subaccount_setup.tf
released/usecases/dev_test_prod_setup/provider.tf

Both BTP and CLOUDFOUNDRY terraform provider versions have been updated to latest (1.7.0 and 1.0.0) in dev_test_prod_setup usecase.
```
[ ] Bugfix
[ ] Feature
```

chore: version update of the providers

---

released/dsag/betriebstag2024/exercises/EXERCISE6/README.md
released/dsag/betriebstag2024/exercises/EXERCISE7/README.md

* Fix setup of CF provider, switch to cloud foundry foundation provider
```
[ ] Bugfix
[ ] Feature
```
n/a

fix: cf provider setup

---

released/SAP-Inside-Tracks/SITBLR_DEC_2024/README.md
released/SAP-Inside-Tracks/SITBLR_DEC_2024/exercises/EXERCISE5/README.md

Few documentation fixes have been updated with this PR
```
[ ] Bugfix
[ ] Feature
```

fix: minor documentation fixes for SIT BLR workshop

---

released/SAP-Inside-Tracks/SITBLR_OCT_2024/readme.md

* Fix broken link of SAO Inside Track README
```
[X] Bugfix
[ ] Feature
```
Closes #372

fix: broken link to SAP Inside Track

---

released/SAP-Inside-Tracks/SITBLR_DEC_2024/exercises/EXERCISE1/README.md
released/SAP-Inside-Tracks/SITBLR_DEC_2024/exercises/EXERCISE4/README.md
released/SAP-Inside-Tracks/SITBLR_DEC_2024/solution/provider.tf

Terraform provider versions have been updated for SIT scripts.
```
[ ] Bugfix
[ ] Feature
```

chore: Update provider versions

---

released/modules/roles/subaccount_role_app_id/README.md
released/modules/roles/subaccount_role_app_id/role_app_id.tf
released/modules/roles/subaccount_role_app_id/role_app_id_outputs.tf
released/modules/roles/subaccount_role_app_id/role_app_id_variables.tf

* Add module to fetch app ID of a role for a subaccount given the role name and the role template name
```
[ ] Bugfix
[X] Feature
```
n/a

feat: add module for fetching app ID for a role

---

released/import/README.md

* Closes #394
```
[ ] Bugfix
[ ] Feature
```
n/a

docs: improvement of import docs

---

released/SAP-Inside-Tracks/SITBLR_MAR_2025/exercises/EXERCISE1/README.md

Documentation fixes for SIT
```
[ ] Bugfix
[ ] Feature
```

chore: update doc fixes

---

.github/workflows/terraform_format_check.yml
.github/workflows/terraform_validate.yml

* update tj-actions/changed-files due to cve
* Details see https://github.com/tj-actions/changed-files/releases/tag/v46.0.1
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: cve in GH Actions
```
See also https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised

chore: update tj-actions/changed-files due to cve

---

.gitignore
released/usecases/trial_integration_suite/01_base_setup_directory/main.tf
released/usecases/trial_integration_suite/01_base_setup_directory/outputs.tf
released/usecases/trial_integration_suite/01_base_setup_directory/provider.tf
released/usecases/trial_integration_suite/01_base_setup_directory/terraform.tfvars.sample
released/usecases/trial_integration_suite/01_base_setup_directory/variables.tf
released/usecases/trial_integration_suite/02_base_setup_subaccount/main.tf
released/usecases/trial_integration_suite/02_base_setup_subaccount/outputs.tf
released/usecases/trial_integration_suite/02_base_setup_subaccount/provider.tf
released/usecases/trial_integration_suite/02_base_setup_subaccount/terraform.tfvars.sample
released/usecases/trial_integration_suite/02_base_setup_subaccount/variables.tf
released/usecases/trial_integration_suite/03_base_setup_integration_app/main.tf
released/usecases/trial_integration_suite/03_base_setup_integration_app/provider.tf
released/usecases/trial_integration_suite/03_base_setup_integration_app/terraform.tfvars.sample
released/usecases/trial_integration_suite/03_base_setup_integration_app/variables.tf
released/usecases/trial_integration_suite/04_setup_oauth_clients/main.tf
released/usecases/trial_integration_suite/04_setup_oauth_clients/provider.tf
released/usecases/trial_integration_suite/04_setup_oauth_clients/terraform.tfvars.sample
released/usecases/trial_integration_suite/04_setup_oauth_clients/variables.tf
released/usecases/trial_integration_suite/README.md

* setup of integration suite with Terraform on a SAP BTP trial account
```
[ ] Bugfix
[X] Feature
```
n/a

feat: setup of integration suite on SAP BTP trial 

---

released/usecases/app_identifer_for_roles/README.md
released/usecases/app_identifer_for_roles/main.tf
released/usecases/app_identifer_for_roles/provider.tf
released/usecases/app_identifer_for_roles/variables.tf

* Add use case for creating role collections with app identifier.
```
[ ] Bugfix
[X] Feature
```
See also https://github.com/SAP/terraform-provider-btp/issues/1086

feat: app identifier for role collections
